### ISSUE TITLE
Investigate sending caching headers to Cloudflare on forms

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop.org#554]
This a ticket in response to #552 for long-term fixes.

The gist is this:

* currently we maintain a list of forms (as Cloudflare pagerules) that tell cloudflare not to cache on these pages
* we'd like to pivot to a more dynamic solution where the origin server (our server) is telling cloudflare directly when not to cache on certain pages.

This would mean we can squash our cloudflare level changes and instead push these directives to our code-base. 

Thats the plan anyways.

Possible reading here:
* https://support.cloudflare.com/hc/en-us/articles/115003206852-Origin-Cache-Control
* https://support.cloudflare.com/hc/en-us/articles/202775670-How-Do-I-Tell-Cloudflare-What-to-Cache-
* https://support.cloudflare.com/hc/en-us/articles/200169266-Does-Cloudflare-honor-my-Expires-and-Cache-Control-headers-for-static-content-

**Comment by harrislapiroff** [comment]
I think the easy thing to do here would be add a `Cache-Control: no-cache` header to all form pages in Wagtail. This would ensure that Cloudflare _never_ caches those pages.

**Comment by harrislapiroff** [comment]
Hm, could also do `Cache-Control: no-store`, which tells cloudflare specifically to not even store anything from the request or response. I assume cloudflare already does this with post requests, but could be reasonable to make it explicit for all forms?

**Comment by harrislapiroff** [comment]
I think `Cache-Control: private` is actually the most appropriate header. Gonna put in a PR for that.

<img width="740" alt="Screen Shot 2019-06-21 at 3 26 15 PM" src="https://user-images.githubusercontent.com/296631/59946583-ed30f980-9438-11e9-9906-b325c14e7c46.png">

**Comment by conorsch** [comment]
> I think the easy thing to do here would be add a Cache-Control: no-cache header to all form pages in Wagtail. This would ensure that Cloudflare never caches those pages.

That's a sound approach, but caveat:

<blockquote>

Cloudflare will honor the Expires and Cache-Control headers if your origin server returns them.

Note that for cached resources, by default Cloudflare will override the Cache-Control header with the value of the "Browser Cache Expiration" option (by default 4 hours), if:

  * the Cache-Control header on the response from the origin server is less than the TTL described in the "Browser Cache Expiration" setting; or,
  *  the origin does not respond with a "Cache-Control" header

</blockquote>

[via [Does Cloudflare honor my Expires and Cache-Control headers for static content?](https://support.cloudflare.com/hc/en-us/articles/200169266-Does-Cloudflare-honor-my-Expires-and-Cache-Control-headers-for-static-content-)] So we'll have to make corresponding infra-land changes in order for the app-provided headers to work. Still in favor! Just noting the need to coordinate during testing.

**Comment by harrislapiroff** [comment]
If I understand it correctly, that's actually the desired effect! Cloudflare overriding the `Cache-Control` header means that they won't cache it, but it _will_ be cached in users' browsers, which is good, because CSRF tokens are distributed on a per-user basis. It's OK for the user to cache the token, we just need to be sure not to serve the same token to multiple users.

**Comment by harrislapiroff** [comment]
But `private` still seems like the more explicit way to indicate that behavior

**Comment by harrislapiroff** [comment]
This is resolved on SDO. Opened https://github.com/freedomofpress/fpf-www-projects/issues/62 to resolve it on other sites.

**Comment by eloquence** [comment]
I'm still encountering this issue on a form that I just created:
https://securedrop.org/report-an-error/

I am getting CSRF errors on this form in private browsing mode. I have not whitelisted it in Cloudflare yet -- my understanding is that this should no longer be necessary.

**Comment by chigby** [comment]
Just putting a second data point out there: I am _not_ getting a CSRF error (or any kind of error) when viewing this page in private browsing mode.. was there a change made to cloudflare?

![image](https://user-images.githubusercontent.com/561931/66341480-659ec600-e915-11e9-851f-384363f0855c.png)

**Comment by eloquence** [comment]
The error only occurs after submitting the page.

**Comment by conorsch** [comment]
> was there a change made to cloudflare?

No changes were made! Holding off until you're through with your investigation, then we can coordinate CF changes if required.

**Comment by chigby** [comment]
Ah, sorry. Thank you! 

I'm going to make some test submissions, if any data gets added it can be safely deleted later.

**Comment by chigby** [comment]
Well, it looks like the problem is that the `Cache-Control` header is not being set to `private` like it's supposed to be:

```bash
$ curl -sI https://securedrop.org/report-an-error/|grep -i cache-control
cache-control: public, max-age=86400
```

Whereas other contact pages such as the [Get Help Form](https://securedrop.org/help/) do have that header correctly set. My suspicion is that some higher level entity, such as Cloudflare, is overriding this header.

I wonder if the string "error" in the URL could be contributing to the problem? @harrislapiroff mentioned that there have been conflicting Cloudflare rules that in the past led to similar unwanted behavior. I'm unable to check directly on the production site or on cloudflare to test this, admittedly somewhat wild, guess. But that's all I'm able to come up with at the moment.

**Comment by harrislapiroff** [comment]
I think a reasonable next step would be to verify this is working as expected on freedom.press (for a new test form) and then compare cf rules. @conorsch might be best placed to do this?

**Comment by eloquence** [comment]
I've created a test form, here:
https://freedom.press/test-form/

Compare it with this form:
https://securedrop.org/report-an-error/

If you load `view-source:https://securedrop.org/report-an-error/` in Firefox private-browsing mode repeatedly, you'll notice that the CSRF token is different for the freedom.press form for each page reload, but is identical for the SDO page for each page reload.

The Cache-Control headers specify a different `max-age` but are both set to `public`:
- `cache-control: public, max-age=86400` on SecureDrop.org
- `cache-control: public, max-age=7200` on freedom.press

The `Expires` header is also different; for the freedom.press page, it's set to expire immediately, whereas the securedrop.org page only expires tomorrow. Cloudflare does honor this header but [according to the docs](https://support.cloudflare.com/hc/en-us/articles/202775670-How-Do-I-Tell-Cloudflare-What-to-Cache-) max-age takes priority.

**Comment by conorsch** [comment]
Thanks for the clear reports, @chigby & @eloquence! Taking a look now...

**Comment by conorsch** [comment]
@eloquence Should be resolved now. Please take it for a spin, and leave a comment in https://github.com/freedomofpress/infrastructure/pull/2155 with your results (positive or negative).
